### ISSUE TITLE
network.covariate.plot

### ISSUE THREAD

**Issue by tommorris168** [MikeJSeo/bnma#1]
network.covariate.plot does not run unless there is a network called "network" in the R environment. "network" may be from a completely different model than intended. I believe the problem is caused by this line
`  if (is.null(network$covariate)) {
    stop("need to provide covariate information to make this plot")
  }`
which should say
`  if (is.null(result$network$covariate)) {
    stop("need to provide covariate information to make this plot")
  }`

**Comment by MikeJSeo** [comment]
Thanks! I'll fix the typo
