### ISSUE TITLE
covariate.type in network.data

### ISSUE THREAD

**Issue by tommorris168** [MikeJSeo/bnma#2]
covariate.type is supposed to be "continuous" or "discrete". In fact, any string is accepted, and if it is not "continuous" then it is interpreted as "discrete". So a spelling mistake like this
`covariate.type = "continous"`
would result in covariate.type being set to "discrete".

**Comment by MikeJSeo** [comment]
hmm I just added an error message when the user specifies covariate.type as something other than continuous or discrete.
